name = "SimpleSim"
uuid = "b9efc609-bc7d-446c-95a0-c858d8725e88"
authors = ["Jannes Huehnerbein <j.huehnerbein@icloud.com>"]
version = "0.1.2"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.9"
